version: "1.0.{build}"
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
branches:
  only:
    - main
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore dotnetInteractiveExtensions.sln --verbosity q
build_script:
  - cmd: dotnet build dotnetInteractiveExtensions.sln -c Release
after_build:
  # For once the build has completed
  - cmd: dotnet pack dotnetInteractiveExtensions.sln -o pacakges -c Release
artifacts:
  - path: "pacakges/**/*.nupkg"
    name: NugetPacakges

clone_depth: 1
test_script:
    - cmd: dotnet test dotnetInteractiveExtensions.sln
deploy:
  - provider: NuGet
    api_key:
      secure: AyHYasuD0QUSf3V8TRXsus8WfKRySs9rBUWMKrahELFCettaqCldEXRFE1U9det/
    skip_symbols: false
    artifact: /.*(\.|\.s)nupkg/
    on:
      branch: main